# Generated by Django 5.0.3 on 2024-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=50)),
                ('cant_paquetes', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
