# Generated by Django 5.0.3 on 2024-04-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('destino', models.CharField(max_length=50)),
                ('cant_paquetes', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
