# Generated by Django 5.0.4 on 2024-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrosActivo',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=50)),
                ('cant_paquetes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(default='Activo', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CarrosEliminado',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=50)),
                ('cant_paquetes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(default='Eliminado', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CarrosMantenimiento',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=50)),
                ('cant_paquetes', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(default='Mantenimiento', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='carros',
            name='activo',
        ),
        migrations.AddField(
            model_name='carros',
            name='estado',
            field=models.CharField(default='Activo', max_length=12),
        ),
    ]
