# Generated by Django 5.0.4 on 2024-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrosactivo_carroseliminado_carrosmantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros_Carga',
            fields=[
                ('matricula', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('anioFabricacion', models.IntegerField(default=0)),
                ('cargaActual', models.IntegerField()),
                ('estado', models.CharField(default='Cargado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('paquetes_pequeños', models.PositiveSmallIntegerField(default=0)),
                ('paquetes_grandes', models.IntegerField(default=0)),
                ('paquetes_fragiles', models.IntegerField(default=0)),
                ('destino', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CarrosActivo',
        ),
        migrations.DeleteModel(
            name='CarrosEliminado',
        ),
        migrations.DeleteModel(
            name='CarrosMantenimiento',
        ),
        migrations.RenameField(
            model_name='carros',
            old_name='destino',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='carros',
            name='cant_paquetes',
        ),
        migrations.AddField(
            model_name='carros',
            name='anioFabricacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carros',
            name='cargaActual',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carros',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
    ]
