# Generated by Django 5.0.4 on 2024-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carros_carga_envios_delete_carrosactivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='estadoCarga',
            field=models.CharField(default='Descargando', max_length=50),
        ),
        migrations.AddField(
            model_name='carros_carga',
            name='estadoCarga',
            field=models.CharField(default='Cargado', max_length=50),
        ),
        migrations.AlterField(
            model_name='carros_carga',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
