# Generated by Django 5.0.4 on 2024-04-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carros_estadocarga_carros_carga_estadocarga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carros_Carga',
        ),
    ]
