# Generated by Django 5.0.4 on 2024-04-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_carros_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='vehiculo_asignado',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
