# Generated by Django 5.0.4 on 2024-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_envios_vehiculo_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='estado',
            field=models.CharField(default='Asignado', max_length=50),
        ),
    ]
